name: "Testes (self-hosted)"

on:
  workflow_dispatch:

jobs:
  testes-self-hosted:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes
        run: yarn run test
